/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controladores.UsuarioController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author tolis
 */
public class FInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form FInicioSesion
     */
    public FInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        imgPersona = new javax.swing.JLabel();
        lbInicioSesion = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();
        labelIdentificacion = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        btIniciarSesion = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();
        tfContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESION");
        setBackground(new java.awt.Color(204, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ginesalud.png"))); // NOI18N
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        imgPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/business_user.png"))); // NOI18N
        jPanel1.add(imgPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, 120));

        lbInicioSesion.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbInicioSesion.setText("INICIO DE SESION");
        jPanel1.add(lbInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jPanel1.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        labelIdentificacion.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelIdentificacion.setText("IDENTIFICACION:");
        jPanel1.add(labelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        labelContraseña.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelContraseña.setText("CONTRASEÑA:");
        jPanel1.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        btIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTON.png"))); // NOI18N
        btIniciarSesion.setBorder(null);
        btIniciarSesion.setBorderPainted(false);
        btIniciarSesion.setContentAreaFilled(false);
        btIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 370, 80));

        tfUsuario.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 270, 40));
        jPanel1.add(tfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarSesionActionPerformed
   try{ 
       //Borrar
   /*    if(true)
       {        FVentanaPrincipal framePrincipal = new FVentanaPrincipal();
        framePrincipal.setVisible(true);
        this.dispose();}
    */   
        if(!tfUsuario.getText().isEmpty() && !tfContrasena.getPassword().toString().isEmpty()){   
        Usuario usuario = new Usuario();
        usuario.setIdUsuario(Integer.parseInt(tfUsuario.getText()));
        usuario.setContrasenaUsuario(new String(tfContrasena.getPassword()));
        UsuarioController usuarioCt = new UsuarioController();
      
        Usuario u = new Usuario();
        u = usuarioCt.consultarUsuario(usuario);
        if(u.getContrasenaUsuario().equals(usuario.getContrasenaUsuario()) && u.getContrasenaUsuario() != null && usuario.getContrasenaUsuario() != null){
        FVentanaPrincipal framePrincipal = new FVentanaPrincipal();
        framePrincipal.setVisible(true);
        this.dispose();
        }
        }else
        {
            JOptionPane.showMessageDialog(null, "Hay campos vacios y/o erroneos");
        }
    }catch(Exception e)
    {}
    }//GEN-LAST:event_btIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciarSesion;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel lbInicioSesion;
    private javax.swing.JPasswordField tfContrasena;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
