/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author tolis
 */
public class FVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FVentanaPrincipal
     */
    public FVentanaPrincipal() {
        initComponents();
        ocultarVentanas();
        Date obj =new Date();
        System.out.println(obj.toString() + "!!");
    }

    public void ocultarVentanas(){
    ventanaCargos.setVisible(false);
    ventanaEntorno.setVisible(false);
    ventanaEquipos.setVisible(false);
    ventanaInsumos.setVisible(false);
    ventanaPacientes.setVisible(false);
    ventanaProcedimientos.setVisible(false);
    ventanaRol.setVisible(false);
    ventanaTipoInsumo.setVisible(false);
    ventanaUsuarios.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBienvenido = new javax.swing.JLabel();
        btPacientes = new javax.swing.JButton();
        ptProcedimientos = new javax.swing.JButton();
        btTipoInsumos = new javax.swing.JButton();
        btInsumos = new javax.swing.JButton();
        btEntorno = new javax.swing.JButton();
        btEquipos = new javax.swing.JButton();
        btCargos = new javax.swing.JButton();
        btRol = new javax.swing.JButton();
        btUsuarios = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        barraLateral = new javax.swing.JLabel();
        barraHorizontal = new javax.swing.JLabel();
        ventanaPacientes = new javax.swing.JInternalFrame();
        labelIdentificacionPacientes = new javax.swing.JLabel();
        labelNombresPacientes = new javax.swing.JLabel();
        labelApellidosPacientes = new javax.swing.JLabel();
        labelTelefonoPacientes = new javax.swing.JLabel();
        labelFechaNacimientoPacientes = new javax.swing.JLabel();
        tfIdentificacionPacientes = new javax.swing.JTextField();
        tfFechaNacimientoPacientes = new javax.swing.JTextField();
        tfNombresPacientes = new javax.swing.JTextField();
        tfApellidosPacientes = new javax.swing.JTextField();
        tfTelefonoPacientes = new javax.swing.JTextField();
        btEjecutarPacientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePacientes = new javax.swing.JTable();
        btImprimirPacientes = new javax.swing.JButton();
        labelTituloPacientes = new javax.swing.JLabel();
        menuPacientes = new javax.swing.JMenuBar();
        opcionConsultarPaciente = new javax.swing.JMenu();
        opConsultarPacientes = new javax.swing.JMenuItem();
        opConsultarPaciente = new javax.swing.JMenuItem();
        opcionAgregarPaciente = new javax.swing.JMenu();
        opcionEditarPaciente = new javax.swing.JMenu();
        opcionEliminarPaciente = new javax.swing.JMenu();
        opcionReportesPaciente = new javax.swing.JMenu();
        opProcedimientosRealizados = new javax.swing.JMenuItem();
        ventanaProcedimientos = new javax.swing.JInternalFrame();
        ventanaTipoInsumo = new javax.swing.JInternalFrame();
        ventanaInsumos = new javax.swing.JInternalFrame();
        ventanaEntorno = new javax.swing.JInternalFrame();
        ventanaEquipos = new javax.swing.JInternalFrame();
        ventanaCargos = new javax.swing.JInternalFrame();
        ventanaRol = new javax.swing.JInternalFrame();
        ventanaUsuarios = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GinesaludSoft");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBienvenido.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        labelBienvenido.setText("BIENVENIDO");
        jPanel1.add(labelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        btPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente.png"))); // NOI18N
        btPacientes.setContentAreaFilled(false);
        btPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, -1));

        ptProcedimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procedimiento.png"))); // NOI18N
        ptProcedimientos.setContentAreaFilled(false);
        jPanel1.add(ptProcedimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 300, -1));

        btTipoInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipoinsumo.png"))); // NOI18N
        btTipoInsumos.setContentAreaFilled(false);
        jPanel1.add(btTipoInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, -1));

        btInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insumo.png"))); // NOI18N
        btInsumos.setContentAreaFilled(false);
        jPanel1.add(btInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 300, -1));

        btEntorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entorno.png"))); // NOI18N
        btEntorno.setContentAreaFilled(false);
        jPanel1.add(btEntorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, -1));

        btEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo.png"))); // NOI18N
        btEquipos.setContentAreaFilled(false);
        jPanel1.add(btEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 300, -1));

        btCargos.setBackground(new java.awt.Color(204, 255, 255));
        btCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargo.png"))); // NOI18N
        btCargos.setContentAreaFilled(false);
        jPanel1.add(btCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 300, -1));

        btRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rol.png"))); // NOI18N
        btRol.setContentAreaFilled(false);
        jPanel1.add(btRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 300, -1));

        btUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btUsuarios.setContentAreaFilled(false);
        jPanel1.add(btUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 300, -1));

        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 300, -1));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ginesalud.png"))); // NOI18N
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, -1, -1));

        barraLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barralateral.png"))); // NOI18N
        barraLateral.setToolTipText("");
        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        barraHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barrahorizontal.png"))); // NOI18N
        jPanel1.add(barraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 80));

        ventanaPacientes.setBackground(new java.awt.Color(255, 255, 255));
        ventanaPacientes.setTitle("PACIENTES");
        ventanaPacientes.setVisible(true);

        labelIdentificacionPacientes.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        labelIdentificacionPacientes.setText("Identificación");

        labelNombresPacientes.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        labelNombresPacientes.setText("Nombres");

        labelApellidosPacientes.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        labelApellidosPacientes.setText("Apellidos");

        labelTelefonoPacientes.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        labelTelefonoPacientes.setText("Telefono");

        labelFechaNacimientoPacientes.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        labelFechaNacimientoPacientes.setText("Fecha de nacimiento");

        tfFechaNacimientoPacientes.setText("yyyy-mm-dd");

        tfTelefonoPacientes.setToolTipText("");

        btEjecutarPacientes.setText("Ejecutar");

        tablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePacientes);

        btImprimirPacientes.setText("Imprimir");

        labelTituloPacientes.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        labelTituloPacientes.setText("OPERACIÓN");

        opcionConsultarPaciente.setText("Consultar");
        opcionConsultarPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N

        opConsultarPacientes.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        opConsultarPacientes.setText("Todos los pacientes");
        opcionConsultarPaciente.add(opConsultarPacientes);

        opConsultarPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        opConsultarPaciente.setText("Paciente");
        opcionConsultarPaciente.add(opConsultarPaciente);

        menuPacientes.add(opcionConsultarPaciente);

        opcionAgregarPaciente.setText("Agregar");
        opcionAgregarPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        menuPacientes.add(opcionAgregarPaciente);

        opcionEditarPaciente.setText("Editar");
        opcionEditarPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        menuPacientes.add(opcionEditarPaciente);

        opcionEliminarPaciente.setText("Eliminar");
        opcionEliminarPaciente.setToolTipText("");
        opcionEliminarPaciente.setActionCommand("Eliminar");
        opcionEliminarPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        menuPacientes.add(opcionEliminarPaciente);

        opcionReportesPaciente.setText("Reportes");
        opcionReportesPaciente.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N

        opProcedimientosRealizados.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        opProcedimientosRealizados.setText("Procedimientos realizados");
        opcionReportesPaciente.add(opProcedimientosRealizados);

        menuPacientes.add(opcionReportesPaciente);

        ventanaPacientes.setJMenuBar(menuPacientes);

        javax.swing.GroupLayout ventanaPacientesLayout = new javax.swing.GroupLayout(ventanaPacientes.getContentPane());
        ventanaPacientes.getContentPane().setLayout(ventanaPacientesLayout);
        ventanaPacientesLayout.setHorizontalGroup(
            ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaPacientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaPacientesLayout.createSequentialGroup()
                        .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificacionPacientes)
                            .addComponent(labelNombresPacientes))
                        .addGap(67, 67, 67)
                        .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ventanaPacientesLayout.createSequentialGroup()
                                .addComponent(tfIdentificacionPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(labelFechaNacimientoPacientes))
                            .addGroup(ventanaPacientesLayout.createSequentialGroup()
                                .addComponent(tfNombresPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelApellidosPacientes)))
                        .addGap(54, 54, 54)
                        .addComponent(tfApellidosPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaPacientesLayout.createSequentialGroup()
                        .addGap(815, 815, 815)
                        .addComponent(tfFechaNacimientoPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(labelTelefonoPacientes)
                        .addGap(34, 34, 34)
                        .addComponent(tfTelefonoPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaPacientesLayout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(btEjecutarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTituloPacientes)
                    .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btImprimirPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        ventanaPacientesLayout.setVerticalGroup(
            ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloPacientes)
                .addGap(27, 27, 27)
                .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificacionPacientes)
                    .addComponent(tfIdentificacionPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNacimientoPacientes)
                    .addComponent(tfFechaNacimientoPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefonoPacientes)
                    .addComponent(tfTelefonoPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ventanaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombresPacientes)
                    .addComponent(tfNombresPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidosPacientes)
                    .addComponent(tfApellidosPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btEjecutarPacientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btImprimirPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(ventanaPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaProcedimientos.setTitle("PROCEDIMIENTOS");
        ventanaProcedimientos.setVisible(true);

        javax.swing.GroupLayout ventanaProcedimientosLayout = new javax.swing.GroupLayout(ventanaProcedimientos.getContentPane());
        ventanaProcedimientos.getContentPane().setLayout(ventanaProcedimientosLayout);
        ventanaProcedimientosLayout.setHorizontalGroup(
            ventanaProcedimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaProcedimientosLayout.setVerticalGroup(
            ventanaProcedimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaProcedimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaTipoInsumo.setTitle("TIPO INSUMO");
        ventanaTipoInsumo.setVisible(true);

        javax.swing.GroupLayout ventanaTipoInsumoLayout = new javax.swing.GroupLayout(ventanaTipoInsumo.getContentPane());
        ventanaTipoInsumo.getContentPane().setLayout(ventanaTipoInsumoLayout);
        ventanaTipoInsumoLayout.setHorizontalGroup(
            ventanaTipoInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaTipoInsumoLayout.setVerticalGroup(
            ventanaTipoInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaTipoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaInsumos.setTitle("INSUMOS");
        ventanaInsumos.setVisible(true);

        javax.swing.GroupLayout ventanaInsumosLayout = new javax.swing.GroupLayout(ventanaInsumos.getContentPane());
        ventanaInsumos.getContentPane().setLayout(ventanaInsumosLayout);
        ventanaInsumosLayout.setHorizontalGroup(
            ventanaInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaInsumosLayout.setVerticalGroup(
            ventanaInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaEntorno.setTitle("ENTORNO");
        ventanaEntorno.setVisible(true);

        javax.swing.GroupLayout ventanaEntornoLayout = new javax.swing.GroupLayout(ventanaEntorno.getContentPane());
        ventanaEntorno.getContentPane().setLayout(ventanaEntornoLayout);
        ventanaEntornoLayout.setHorizontalGroup(
            ventanaEntornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaEntornoLayout.setVerticalGroup(
            ventanaEntornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaEntorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaEquipos.setTitle("EQUIPOS");
        ventanaEquipos.setVisible(true);

        javax.swing.GroupLayout ventanaEquiposLayout = new javax.swing.GroupLayout(ventanaEquipos.getContentPane());
        ventanaEquipos.getContentPane().setLayout(ventanaEquiposLayout);
        ventanaEquiposLayout.setHorizontalGroup(
            ventanaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaEquiposLayout.setVerticalGroup(
            ventanaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaCargos.setTitle("CARGOS");
        ventanaCargos.setVisible(true);

        javax.swing.GroupLayout ventanaCargosLayout = new javax.swing.GroupLayout(ventanaCargos.getContentPane());
        ventanaCargos.getContentPane().setLayout(ventanaCargosLayout);
        ventanaCargosLayout.setHorizontalGroup(
            ventanaCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaCargosLayout.setVerticalGroup(
            ventanaCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaRol.setTitle("ROLES");
        ventanaRol.setVisible(true);

        javax.swing.GroupLayout ventanaRolLayout = new javax.swing.GroupLayout(ventanaRol.getContentPane());
        ventanaRol.getContentPane().setLayout(ventanaRolLayout);
        ventanaRolLayout.setHorizontalGroup(
            ventanaRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaRolLayout.setVerticalGroup(
            ventanaRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        ventanaUsuarios.setTitle("USUARIOS");
        ventanaUsuarios.setVisible(true);

        javax.swing.GroupLayout ventanaUsuariosLayout = new javax.swing.GroupLayout(ventanaUsuarios.getContentPane());
        ventanaUsuarios.getContentPane().setLayout(ventanaUsuariosLayout);
        ventanaUsuariosLayout.setHorizontalGroup(
            ventanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        ventanaUsuariosLayout.setVerticalGroup(
            ventanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );

        jPanel1.add(ventanaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1570, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
int resp = JOptionPane.showConfirmDialog(rootPane, "¿QUIERE SALIR DE LA APLICACION?", "SALIR", JOptionPane.YES_NO_OPTION);
if(resp == 0){
System.exit(0);
}
    }//GEN-LAST:event_btSalirActionPerformed

    private void btPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacientesActionPerformed
ocultarVentanas();
ventanaPacientes.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraHorizontal;
    private javax.swing.JLabel barraLateral;
    private javax.swing.JButton btCargos;
    private javax.swing.JButton btEjecutarPacientes;
    private javax.swing.JButton btEntorno;
    private javax.swing.JButton btEquipos;
    private javax.swing.JButton btImprimirPacientes;
    private javax.swing.JButton btInsumos;
    private javax.swing.JButton btPacientes;
    private javax.swing.JButton btRol;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btTipoInsumos;
    private javax.swing.JButton btUsuarios;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellidosPacientes;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel labelFechaNacimientoPacientes;
    private javax.swing.JLabel labelIdentificacionPacientes;
    private javax.swing.JLabel labelNombresPacientes;
    private javax.swing.JLabel labelTelefonoPacientes;
    private javax.swing.JLabel labelTituloPacientes;
    private javax.swing.JMenuBar menuPacientes;
    private javax.swing.JMenuItem opConsultarPaciente;
    private javax.swing.JMenuItem opConsultarPacientes;
    private javax.swing.JMenuItem opProcedimientosRealizados;
    private javax.swing.JMenu opcionAgregarPaciente;
    private javax.swing.JMenu opcionConsultarPaciente;
    private javax.swing.JMenu opcionEditarPaciente;
    private javax.swing.JMenu opcionEliminarPaciente;
    private javax.swing.JMenu opcionReportesPaciente;
    private javax.swing.JButton ptProcedimientos;
    private javax.swing.JTable tablePacientes;
    private javax.swing.JTextField tfApellidosPacientes;
    private javax.swing.JTextField tfFechaNacimientoPacientes;
    private javax.swing.JTextField tfIdentificacionPacientes;
    private javax.swing.JTextField tfNombresPacientes;
    private javax.swing.JTextField tfTelefonoPacientes;
    private javax.swing.JInternalFrame ventanaCargos;
    private javax.swing.JInternalFrame ventanaEntorno;
    private javax.swing.JInternalFrame ventanaEquipos;
    private javax.swing.JInternalFrame ventanaInsumos;
    private javax.swing.JInternalFrame ventanaPacientes;
    private javax.swing.JInternalFrame ventanaProcedimientos;
    private javax.swing.JInternalFrame ventanaRol;
    private javax.swing.JInternalFrame ventanaTipoInsumo;
    private javax.swing.JInternalFrame ventanaUsuarios;
    // End of variables declaration//GEN-END:variables
}
